### ISSUE TITLE
NVG у повстанцев?

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO26_First_Steps.zargabad#1]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_gear/Kits.sqf#L46

**Comment by Comrade333** [comment]
убрал

**Comment by 10Dozen** [comment]
Теперь если ночью запускать то даже машин не видно - ни где стоят, ни куда грузится

<img src='http://puu.sh/AFCzq/d5c3225cd0.jpg' />

**Comment by 10Dozen** [comment]
Опционально -- найти дату со светлой ночью и/или фонариков выдать

**Comment by Comrade333** [comment]
сделал более светлую ночь
