### ISSUE TITLE
Скущный дефолтный эндинг

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#19]
Надо интересно чтобы был смысл побеждать

**Comment by Comrade333** [comment]
добавил несколько концовок

**Comment by 10Dozen** [comment]
Побольше АллахАкбар и Аззубилях в ендингах. Мы ж за бабахов играем или нет?

**Comment by 10Dozen** [comment]
Попроси воншира если фантазии нет

**Comment by Comrade333** [comment]
поисправлял немного
