### ISSUE TITLE
Тайтл миссии хуйовый

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#21]
CO26 Operation first step

зачем оперейшен? почему все мелкими буквами? Почему краткое описание миссии не описывает ничо?

**Comment by Comrade333** [comment]
убрал операцию, с больших буков слова

**Comment by 10Dozen** [comment]
Сам репозиторий переименуй, а то в списке миссий остается оперейшн

**Comment by Comrade333** [comment]
переименовал
