### ISSUE TITLE
Какого члена опять хуйня в интро?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#32]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/Modules/IntroText/Settings.sqf#L5

Ты буквы читать умеешь вообще? Блять там же написано в каком формате кастомную задвать ИЛИ вообще не трогать если использовать дату из настроек миссии.

НАХУЯ?!
НАХУЯ БЛЯДЬ ТЫ МАЛО ТОГО ЧТО ПИШЕШЬ __РУКАМИ__ дату которую можно выставить в редакторе, так еще и ДЕЛАЕШЬ ЭТО НЕПРАВИЛЬНА
ААААААААА БЛЯТЬ, НУ ЧТО ЗА ХЕРНЯ

**Comment by Comrade333** [comment]
написал правильна

**Comment by 10Dozen** [comment]
почему вручную дата задана?

**Comment by Comrade333** [comment]
поправил
