### ISSUE TITLE
Опять ОПЕРАЦИЯ у голожопых бабахов. ну ептвоюжмать

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#33]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/Modules/IntroText/Settings.sqf#L13

ФЙОРСТ СТЕПС конечно дохуя крута, согласен. Но схуяли по АНГЛИЙСКИ если мы РУССКИЕ ЛЮДИ, а играем за АРАБОВ. Ну откуда ж блет ИНЛИШ ЛАНГУАЖЕ?

**Comment by Comrade333** [comment]
терь без операций

**Comment by 10Dozen** [comment]
Что такоей Сомбат Енсоунтер?

**Comment by Comrade333** [comment]
Баявое столкновение
переименовал
