### ISSUE TITLE
Опять кривые кондишены

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#34]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/Modules/MissionConditions/Settings.sqf#L51

во 1) хуле ты мне сделаешь вовторых пошел нахуй втетьих 3)что ты мне сделаешь, я в другом городе за мат извени

По крайней мере:
1) Вместо кавычек - фигурные скобки
2) ГДЕ БЛЕТ ОПЕРАТОРЫ? && || 
3) Убитые/трупы ВИПов в деревне это тоже успех миссии
4) Зачем ждать ВСЕХ игроков в деревне для успеха?
5) Где неполные концовки? Если убили офицера но не привезли старейшин - это полный провал? Если спасли старейшин но погиб один вип - это полный провал?

**Comment by Comrade333** [comment]
передалал

**Comment by 10Dozen** [comment]
MissionCondition3 означает:
VIP1 или VIP2 на базу увезли
+ жив VIP1 или VIP2

т.е. мертвый VIP1 на базе == успех или мертвый VIP2 на базе == успех

нада делать: 

( 
   ( alive VIP1 && !alive VIP2 && VIP1 inArea baseTrg )
   || ( alive VIP2 && !alive VIP1 && VIP1 inArea baseTrg )
) && !alive KILL
&& {call fnc_CheckPlayersReturned}

**Comment by Comrade333** [comment]
еще раз переделал
