### ISSUE TITLE
Нинужны нам медэвак запросы если мы голожопые

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#36]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/Modules/tSNotes/Settings.sqf#L8-L9

**Comment by Comrade333** [comment]
false

**Comment by 10Dozen** [comment]
шта?

**Comment by Comrade333** [comment]
выставил на фолс
