### ISSUE TITLE
Магические ящики на базе

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#40]
Есть ли какоето осмысленное объяснение почему в таком ОГРОМНОМ ящике лежит 15 винтовок по 2 метра каждая

<img src='http://puu.sh/AFCY3/d48827bc7b.jpg' />

А вот в этом малюсеньком спичесном коробке не лежит нихуя?

<img src='http://puu.sh/AFCZP/6acceb8065.jpg' />

**Comment by Comrade333** [comment]
Для большого ящика накинул кит с формой и рациями
перепробовал множество ящиков для винтовок, кроме этих никакие не тащились
