### ISSUE TITLE
Индур бехавиор

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#41]
Вообще говоря вот эти лимовские костыли 

commandStop (units this); 
this forceSpeed 0;

делают так, что ботики даже обнаружив противника покорно стоят на том же месте и ждут пока их убьют:
<img src='http://puu.sh/AFE3l/9cbc1b2208.jpg'/>
<img src='http://puu.sh/AFE3V/114c6cc25a.jpg'/>

Сам по себе индур работает так, что после того как бот противника заспотил  - он идет его убивать и просто так пострелять и спрятаться за углом не получится, ботик придет и жопу выебет.

А лимокостыли как обычно делают какуюто хуйню с непонятной целью. Бот-турель который не двигается с места даже под огнем - оу май...

**Comment by Comrade333** [comment]
Оставил эти костыли для снуперов на вышках и челиков в бункерах
остальным убрал
