### ISSUE TITLE
Почему бы название миссии не писать с заглавных?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#6]
Например CO26_Operation_First_Steps ?
В общем случае Оперейшн в заголовке миссии можно опускать: CO26_First_Steps.
Тем более что повстанцы врядли называют свои набеги ОПЕРЕЙШЕНами

**Comment by OneScheer** [comment]
Дурацкая привычка сувать в каждое название Operation образовалась у Гео и теперь уже у Комрада.

**Comment by Comrade333** [comment]
исправил
