### ISSUE TITLE
Брефенг с ошипками и без души

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#8]
Предложения по исправлению https://github.com/rempopo/CO26_Operation_first_steps.zargabad/pull/7

**Comment by Comrade333** [comment]
скопировал из предложки
но я жи не писатиль, я про100 обыватель из ебеней(((

**Comment by 10Dozen** [comment]
Ничего не скопировано, брифинг остался без изменений
