### ISSUE TITLE
Неочевидное расположение машин.

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_First_Steps.zargabad#9]
Зачем бежать из застройки чтобы решить кто куда садиться? Почему не поставить поближе к машинам или машины поближе к игрокам?

**Comment by Comrade333** [comment]
поставил челиков поближе

**Comment by 10Dozen** [comment]
Добавь хоть какое-нибудть освещение (фонарь поставь или хотя бы костер). В ночной версии нихуя не понятно где машины искать

**Comment by Comrade333** [comment]
добавил костер
